import 'fake-indexeddb/auto'
import { afterEach, beforeEach, describe, expect, it } from 'vitest'
import { cleanup, render, screen, waitFor } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { addDays } from '@/core/engine/dateUtils'
import { todayKey } from '@/core/dateKeys'
import { useAppStore } from '@/core/store/useAppStore'
import { Toaster } from '@/components/ui/sonner'
import { CalendarView } from '../index'
import { autoOpenStorageKey } from '../auto-open'

const store = () => useAppStore.getState()

function cellByDate(date: string): HTMLElement | null {
  return screen.getAllByTestId('day-cell').find((element) => element.getAttribute('data-date') === date) ?? null
}

async function setup() {
  useAppStore.setState({ hydrated: false })
  await useAppStore.getState().hydrate()
  await useAppStore.getState().clearAllData()
  sessionStorage.setItem(autoOpenStorageKey(todayKey()), 'consumed')
}

async function seedPeak() {
  const start = addDays(todayKey(), -20)
  const cycle = await store().setNewCycle(start)
  await store().addDayRecord(cycle.id, start, 1, { bloodFlow: 'medium' })
  await store().addDayRecord(cycle.id, addDays(start, 13), 14, { monitor: 'peak' })
  return { start, cycle }
}

beforeEach(async () => {
  Object.defineProperty(window, 'matchMedia', {
    writable: true,
    value: () => ({
      matches: false,
      media: '',
      onchange: null,
      addListener: () => {},
      removeListener: () => {},
      addEventListener: () => {},
      removeEventListener: () => {},
      dispatchEvent: () => false,
    }),
  })
  await setup()
})

afterEach(() => {
  cleanup()
})

describe('Calendar post-Peak fill presentation', () => {
  it('marks an autogenerated Low differently from a user record', async () => {
    const { start } = await seedPeak()
    render(<CalendarView />)

    const generatedDate = addDays(start, 18)
    const cell = await waitFor(() => {
      const found = cellByDate(generatedDate)
      expect(found).not.toBeNull()
      return found!
    })
    expect(cell.getAttribute('data-origin')).toBe('inferred')
    expect(cell.querySelector('[title="Monitor: low"]')).not.toBeNull()
    expect(cell.querySelector('[title="Assumed data"]')).not.toBeNull()
  })

  it('hides inferred rows while the algorithm is off but keeps user records visible', async () => {
    const { start } = await seedPeak()
    render(<CalendarView />)

    const generatedDate = addDays(start, 18)
    await waitFor(() => expect(cellByDate(generatedDate)?.getAttribute('data-origin')).toBe('inferred'))
    await store().updateSettings({ algorithmEnabled: false })

    await waitFor(() => {
      const generatedCell = cellByDate(generatedDate)
      expect(generatedCell?.getAttribute('data-origin')).not.toBe('inferred')
      expect(generatedCell?.querySelector('[title="Monitor: low"]')).toBeNull()
      expect(generatedCell?.querySelector('[title="Assumed data"]')).toBeNull()
    })
    expect(cellByDate(addDays(start, 13))?.querySelector('[title="Monitor: peak"]')).not.toBeNull()
    expect(store().dayRecords.some((record) => record.date === generatedDate && record.dataOrigin === 'inferred')).toBe(true)
  })

  it('explains assumed data in the legend and accessible cell label', async () => {
    const { start } = await seedPeak()
    render(<CalendarView />)

    const generatedDate = addDays(start, 18)
    const cell = await waitFor(() => {
      const found = cellByDate(generatedDate)
      expect(found).not.toBeNull()
      return found!
    })
    expect(screen.getByText('Assumed data')).toBeInTheDocument()
    expect(cell.getAttribute('aria-label')).toContain('assumed data')
  })

  it('rerenders the stale inferred tail after a backfilled Menses boundary', async () => {
    const { start, cycle } = await seedPeak()
    render(<CalendarView />)

    const boundary = addDays(start, 18)
    const staleGeneratedDate = addDays(start, 19)
    await waitFor(() => expect(cellByDate(staleGeneratedDate)?.getAttribute('data-origin')).toBe('inferred'))

    await store().addDayRecord(cycle.id, boundary, 19, { bloodFlow: 'heavy' })

    await waitFor(() => {
      expect(cellByDate(boundary)?.getAttribute('data-origin')).toBe('user')
      expect(cellByDate(boundary)?.querySelector('[title="Menses"]')).not.toBeNull()
      expect(cellByDate(staleGeneratedDate)?.getAttribute('data-origin')).not.toBe('inferred')
      expect(cellByDate(staleGeneratedDate)?.querySelector('[title="Monitor: low"]')).toBeNull()
    })
    expect(store().cycles.map((item) => item.day1)).toContain(boundary)
  })

  it('leaves pre-anchor gaps blank in user-anchor mode', async () => {
    const start = addDays(todayKey(), -20)
    const cycle = await store().setNewCycle(start)
    await store().updateSettings({ postPeakFillMode: 'after-user-low' })
    await store().addDayRecord(cycle.id, start, 1, { bloodFlow: 'medium' })
    await store().addDayRecord(cycle.id, addDays(start, 13), 14, { monitor: 'peak' })
    await store().addDayRecord(cycle.id, addDays(start, 18), 19, { monitor: 'low' })
    render(<CalendarView />)

    await waitFor(() => expect(cellByDate(addDays(start, 19))?.getAttribute('data-origin')).toBe('inferred'))
    expect(cellByDate(addDays(start, 17))?.getAttribute('data-origin')).not.toBe('inferred')
    expect(cellByDate(addDays(start, 18))?.getAttribute('data-origin')).not.toBe('inferred')
  })

  it('keeps an explicitly deleted assumed date absent after reconciliation', async () => {
    const user = userEvent.setup()
    const { start } = await seedPeak()
    render(<CalendarView />)

    const generatedDate = addDays(start, 18)
    await waitFor(() => expect(cellByDate(generatedDate)?.getAttribute('data-origin')).toBe('inferred'))
    await user.click(cellByDate(generatedDate)!)
    await user.click(await screen.findByTestId('delete-record'))

    await waitFor(() => expect(cellByDate(generatedDate)?.getAttribute('data-origin')).not.toBe('inferred'))
    expect(cellByDate(generatedDate)?.querySelector('[title="Monitor: low"]')).toBeNull()
  })

  it('lets the user override an assumed record and removes the generated marker', async () => {
    const user = userEvent.setup()
    const { start } = await seedPeak()
    render(
      <>
        <CalendarView />
        <Toaster />
      </>,
    )

    const generatedDate = addDays(start, 18)
    await waitFor(() => expect(cellByDate(generatedDate)?.getAttribute('data-origin')).toBe('inferred'))
    await user.click(cellByDate(generatedDate)!)
    expect(await screen.findByTestId('assumed-data-label')).toBeInTheDocument()

    await user.click(screen.getByRole('button', { name: 'Peak' }))
    await user.click(screen.getByRole('button', { name: 'Save' }))

    await waitFor(() => expect(cellByDate(generatedDate)?.getAttribute('data-origin')).toBe('user'))
    expect(cellByDate(generatedDate)?.querySelector('[title="Assumed data"]')).toBeNull()
  })
})
